name: photo-processor

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - ./cache:/app/cache
      - ./logs:/app/logs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
