version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./static:/app/static
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
